"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ApiError } from "@/lib/api/client";
import {
  payrollApi,
  type ApiPayrollSettings,
  type PayrollSettingsPatch,
  type PayrollSettingsRow,
  type StatutoryNotice,
} from "@/lib/api/payroll";
import { useDemoDeductions } from "./features";
import { useSession } from "./session";
import { useRevalidation } from "@/lib/revalidate";

/**
 * The three switches that decide what the payroll engine computes.
 *
 * ## Why this is its own store
 *
 * `lib/payroll/use-settings.ts` holds the whole settings object in
 * **localStorage**, and every screen that reads a rate reads it from there. That
 * is fine for a working month or a salary split — nothing outside this browser
 * depends on them — and it is not fine for these three, because whether a company
 * deducts PAYE has to reach `PayrollSettings` on the API or the switch is
 * decoration. A switch that looks saved and moves no payslip is the same failure
 * as a green "Paid" against money nobody transferred.
 *
 * So these three are API-backed and the rest of that screen is not, deliberately
 * and narrowly. Converting the whole local store is a larger job — it is read
 * synchronously from inside four other stores — and doing it as a side effect of
 * this change would put loading states into the attendance and overtime screens.
 *
 * ## Demo mode reads the shipped defaults and refuses the write
 *
 * The same split `useScoringWeights` makes, for the same reason. Reading is how
 * somebody sees what the switches are; writing changes what every payslip in a
 * real company deducts, and the demo payslips are **fixed illustrative rows
 * generated by the API's engine on its defaults** (`lib/mock/demo-payslips`), so
 * a local switch could not move a single figure. Showing it as saved would be a
 * lie about the one thing on the screen that costs money.
 *
 * The setup wizard's own answers do persist locally, because there the value is
 * the answer rather than the arithmetic — see `DemoState.deductions`.
 */

export type DeductionSwitchState = {
  /** Null until the first read lands. Never guessed from the defaults. */
  settings: ApiPayrollSettings | null;
  /** True when the API has no stored row, so these are the engine's defaults. */
  defaults: boolean;
  notices: StatutoryNotice[];
  loading: boolean;
  error: string | null;
  /** False with no API. Writing is refused and the screen says why. */
  available: boolean;
  save: (patch: PayrollSettingsPatch) => Promise<void>;
  reload: () => void;
};

/**
 * What a company with no API is looking at.
 *
 * The engine's own defaults, stated as defaults. `settings` is a whole row so a
 * screen renders one shape in both modes; `defaults: true` is what stops the
 * screen presenting them as decisions somebody made.
 */
const DEMO_ROW: PayrollSettingsRow = {
  workingDaysPerMonth: 22,
  basicPercent: "0.6",
  housingPercent: "0.25",
  transportPercent: "0.15",
  payeEnabled: true,
  pensionEnabled: true,
  pensionEmployeeRate: "0.08",
  pensionEmployerRate: "0.1",
  pensionOnBasic: true,
  pensionOnHousing: true,
  pensionOnTransport: true,
  /* False, matching the real schema default — see `demoDefaults()` in
     `features.ts`. Unlike PAYE and pension, NHF has no equivalent history of
     "every company was already doing this", so a company with no answer of
     its own gets nothing deducted for it rather than the statutory rate. */
  nhfEnabled: false,
  nhfRate: "0.025",
  nhfOnGross: false,
  netSwingThreshold: "0.25",
  requireBankAccount: true,
  requirePensionPin: true,
  blockNegativeNet: true,
};

const DEMO_SETTINGS: ApiPayrollSettings = {
  settings: DEMO_ROW,
  defaults: true,
  /* Absent rather than a count. A demo headcount would put a number into a
     sentence about a statutory threshold, and the demo directory is not a
     payroll. `statutoryNotices` states the rule without a figure when it is
     given none, which is the honest version. */
  headcount: 0,
  issues: [],
  notices: [],
};

export const DEMO_REFUSAL =
  "Switching a statutory deduction off changes what every payslip in the " +
  "company deducts, so it needs the API. The payslips in this demo are fixed " +
  "illustrative figures and a switch here would move none of them \u2014 the " +
  "demo payroll run refuses instead of showing figures that contradict this " +
  "screen. What each answer commits you to under Nigerian law is written on " +
  "the server, beside the engine that reads it, so it is not repeated here.";

export function useDeductionSwitches(): DeductionSwitchState {
  const { isConnected, isLoading, can } = useSession();
  /* `GET /payroll/settings` is `VIEW_SALARIES` (`modules/payroll/router.ts`).
     What a company deducts is information about what people earn, which is why
     it is gated at all — so a reader without it gets nothing, quietly. */
  const mayRead = can("VIEW_SALARIES");
  /* The demo answer to the two setup questions. Read so this screen and the
     wizard cannot disagree: the wizard persists "we do not deduct PAYE" and a
     settings screen still reporting PAYE as deducted would be two demo screens
     making opposite claims about money. */
  const demoAnswers = useDemoDeductions();
  const [tick, setTick] = useState(0);
  const [fetched, setFetched] = useState<{
    key: string;
    settings: ApiPayrollSettings | null;
    error: string | null;
  } | null>(null);

  const key = `${String(isConnected)}|${tick}`;

  /* The demo value never touches state — same rule as `lib/store/shifts.ts`.
     Writing it into `useState` makes the offline branch a render cascade, and it
     makes "loading" and "there is nothing to load" the same flag. */
  const demo = useMemo<ApiPayrollSettings>(
    () =>
      demoAnswers === null
        ? DEMO_SETTINGS
        : {
            ...DEMO_SETTINGS,
            settings: { ...DEMO_ROW, ...demoAnswers },
          },
    [demoAnswers],
  );

  /* Re-ask when somebody comes back to the window. Not in the key below,
     so the answer is replaced without the screen flashing a skeleton. */
  const revalidation = useRevalidation();
  useEffect(() => {
    if (isLoading || !isConnected || !mayRead) return;
    let cancelled = false;
    const controller = new AbortController();

    void (async () => {
      try {
        const settings = await payrollApi.settings(controller.signal);
        if (!cancelled) setFetched({ key, settings, error: null });
      } catch (error) {
        if (error instanceof DOMException && error.name === "AbortError") return;
        if (!cancelled) {
          setFetched({
            key,
            settings: null,
            error:
              error instanceof ApiError
                ? error.message
                : "Could not read what this company deducts.",
          });
        }
      }
    })();

    return () => {
      cancelled = true;
      controller.abort();
    };
  }, [key, isConnected, isLoading, mayRead, revalidation]);

  const save = useCallback(
    async (patch: PayrollSettingsPatch) => {
      if (!isConnected) throw new Error(DEMO_REFUSAL);
      const settings = await payrollApi.updateSettings(patch);
      /* The response is the new truth, including the notices, so nothing here
         re-derives what switching one off means. */
      setFetched({ key, settings, error: null });
    },
    [isConnected, key],
  );

  const reload = useCallback(() => setTick((n) => n + 1), []);

  if (!isConnected) {
    return {
      settings: demo,
      defaults: true,
      notices: [],
      loading: isLoading,
      error: null,
      available: false,
      save,
      reload,
    };
  }

  /* Matched on the key, so a reload does not show the previous answer as
     current. Absent is loading, never "nothing is deducted". */
  const current = fetched?.key === key ? fetched : null;
  return {
    settings: current?.settings ?? null,
    defaults: current?.settings?.defaults ?? false,
    notices: current?.settings?.notices ?? [],
    loading: current === null,
    error: current?.error ?? null,
    available: true,
    save,
    reload,
  };
}
