"use client";

import {
  useCallback,
  useEffect,
  useMemo,
  useState,
  useSyncExternalStore,
} from "react";
import { ApiError } from "@/lib/api/client";
import {
  payrollApi,
  type ApprovedRun,
  type Discrepancy,
  type ExclusionChange,
  type PayrollRun,
  type PayrollRunDetail,
  type PayrollRunStatus,
  type Payslip,
  type PayslipCounts,
  type PayslipDelivery,
  type PayslipLine,
  type PayslipListParams,
  type PayslipPage,
  type OwnPayslip,
  type PayslipRunSummary,
  type PreparedRun,
  type ReliefRegime,
  type RunException,
  type RunExclusion,
  type BonusChange,
  type MonthlyPayChange,
  type OvertimeOverrideChange,
  type OvertimeOverrideKind,
  type TaxOverrideChange,
} from "@/lib/api/payroll";
import {
  DEMO_PAYSLIP_BASIS,
  payslipFiguresFor,
  type DemoPayslipFigures,
} from "@/lib/mock/demo-payslips";
import type { PayrollSettings } from "@/lib/payroll/settings";
import { usePayrollSettings } from "@/lib/payroll/use-settings";
import { useDemoDeductions } from "./features";
import {
  PREVIOUS_NET,
  SCHEDULED_DEDUCTIONS,
  runPeopleFrom,
  type PayrollEmployee,
} from "@/lib/mock/payroll";
import { TODAY } from "@/lib/today";
import { createPersistedState } from "./persisted";
import { useEmployeeStore } from "./employees";
import { useSession } from "./session";
import { useRevalidation } from "@/lib/revalidate";

/**
 * Payroll runs, from whichever source is available.
 *
 * Connected → `/api/v1/payroll`. Demo → a run computed here, in this browser.
 * Every screen calls these hooks and does not care which it got; `connected`
 * comes back on every result so the screen can say which one it is showing.
 *
 * ## The demo run is computed, not written down
 *
 * A draft run's figures are **recomputed from the live employee directory on
 * every render**. That is not laziness — it is the property the product is
 * selling. Fix a missing account number on somebody's record and the blocker
 * clears here without a reload, exactly as it does against the API, because in
 * both modes the run is a function of the directory rather than a copy of it.
 *
 * Approval is where that stops. An approved run carries a **frozen** snapshot,
 * and from then on the figures come out of the snapshot no matter what the
 * directory says afterwards. That is the same one-way door the API implements,
 * for the same reason: a payslip from 2026 has to explain itself in 2029, and
 * re-deriving it from tomorrow's records would silently rewrite it.
 *
 * ## Where the demo’s figures come from, now that there is no second engine
 *
 * There used to be a copy of the payroll engine in this browser, and demo runs
 * were computed with it. It was left on the 2011 PAYE bands when the Nigeria Tax
 * Act 2025 went into the API, so it quoted last year’s tax for a while. It is
 * deleted, and nothing here computes statutory anything.
 *
 * Demo payslips now read **fixed illustrative figures** from
 * `lib/mock/demo-payslips.ts`, generated by the API’s own engine for the demo
 * directory’s salaries and labelled illustrative on every screen that shows
 * them. A payroll product whose payroll module shows nothing without a database
 * cannot be demonstrated, and a second implementation of tax law is what we just
 * finished removing — fixed output is the third option, and the only honest one.
 *
 * Two things make the fixture refuse rather than mislead, both as BLOCKERs on
 * the run:
 *
 * - **A salary it has no row for.** Edit somebody’s pay in demo mode, or create
 *   a person, and there is no figure to show. `payslipFiguresFor` returns null
 *   and the run names them.
 * - **Settings changed away from the demo defaults.** The figures were generated
 *   on one set of rates. Change a pension rate and they no longer describe what
 *   this company pays, so they are withheld rather than relabelled.
 *
 * ## What the demo deliberately does not do
 *
 * - **No allowances.** The fixture is the plainest possible payslip — contract
 *   salary, statutory deductions, nothing else. Allowances need the API, and the
 *   screens say so.
 * - **No proration.** Unpaid days come from the attendance roster, which the
 *   demo run does not read. Every demo payslip is a full month.
 * - **Nothing statutory.** Post-tax deductions are applied on top of the
 *   fixture, which is exact integer arithmetic and needs no engine: an after-tax
 *   deduction takes exactly its own amount off take-home, capped at what is
 *   there.
 *
 * ## Exclusions work in demo mode, and that is a decision
 *
 * `store/departments.ts` refuses every write offline, because a department is a
 * payroll reporting boundary and a tree built in one browser would never reach a
 * run — building one would teach the opposite of how the product works.
 * `store/shifts.ts` argues the other way for the rota, because nothing else in
 * the frontend reads it. **An exclusion is the shifts case, not the departments
 * case**: it is one run's decision about one person, it lives in the same
 * persisted record as the run it belongs to, and nothing outside these hooks
 * reads it. So the demo can show the whole loop — blocker, exclude with a reason,
 * recalculate, approve — which is the loop the feature exists for and the thing a
 * buyer needs to watch happen.
 *
 * It behaves like the API in the two ways that matter. The blocker **stays** a
 * blocker until somebody excludes that person, so the safe outcome is the one you
 * get by doing nothing. And the exclusion is keyed to the period, so preparing
 * the next month brings them back with nothing to remember.
 */

/* ------------------------------------------------------------ demo storage */

type DemoExclusion = {
  employeeId: string;
  reason: string;
  /** Who decided, as a name — the demo signs in as a person, not an id. */
  decidedBy: string | null;
  excludedAt: string;
};

type DemoRunRecord = {
  /** `YYYY-MM`. One run per period, same as the API's unique constraint. */
  period: string;
  payDate: string;
  label: string | null;
  status: PayrollRunStatus;
  preparedAt: string;
  approvedAt: string | null;
  /**
   * People deliberately left off **this** period, with the reason.
   *
   * On the run rather than on the employee, exactly as `PayrollExclusion` hangs
   * off `PayrollRun`: a new period starts with none, so anybody left off comes
   * back by themselves and nothing has to remember to put them there. Optional,
   * because a payload persisted before this field existed has none — read it
   * through `exclusionsOf` and never directly.
   */
  exclusions?: DemoExclusion[];
  /** Written at approval. Null while the run is still a draft. */
  frozen: PayrollRunDetail | null;
};

const exclusionsOf = (record: DemoRunRecord): DemoExclusion[] =>
  record.exclusions ?? [];

type DemoState = { runs: DemoRunRecord[] };

const CURRENT_PERIOD = TODAY.slice(0, 7);

/**
 * The demo starts with the current period already prepared and awaiting
 * approval, because that is the state a payroll demo is worth opening on.
 *
 * Only one run, and no invented history: prior periods appear as somebody
 * prepares them. Four rows of plausible-looking past totals would be four
 * figures nobody could reconcile against the payslips underneath them, which is
 * the failure this product exists to refuse.
 */
const DEMO_EMPTY: DemoState = {
  runs: [
    {
      period: CURRENT_PERIOD,
      payDate: `${CURRENT_PERIOD}-28`,
      label: null,
      status: "IN_REVIEW",
      preparedAt: `${TODAY}T08:30:00.000Z`,
      approvedAt: null,
      exclusions: [],
      frozen: null,
    },
  ],
};

const demoStore = createPersistedState<DemoState>({
  key: "approvehr.payroll.runs",
  empty: DEMO_EMPTY,
  /* 2: a run carries its own exclusions. `exclusionsOf` reads a version 1
     payload as having none rather than stranding it, so the bump is belt and
     braces rather than the thing keeping old data working. */
  version: 2,
});

const useDemoRuns = (): DemoState =>
  useSyncExternalStore(
    demoStore.subscribe,
    demoStore.read,
    demoStore.getServerSnapshot,
  );

/* ------------------------------------------------------- demo computation */

const demoRunId = (period: string) => `demo-${period}`;
const demoPayslipId = (period: string, employeeId: string) =>
  `demo-${period}-${employeeId}`;

/** Naira float → whole kobo. The demo's own rounding boundary. */
const kobo = (naira: number) => Math.round(naira * 100);

/**
 * Which relief regime the fixture's figures were computed under.
 *
 * Read off `DEMO_PAYSLIP_BASIS` rather than assumed, because that block records
 * the schedule the API's engine actually used — currently rent relief, with
 * nothing declared, so every `reliefMonthlyKobo` in the fixture is zero. A
 * payslip that showed that zero under "consolidated relief allowance" would be
 * naming a relief the Nigeria Tax Act 2025 abolished, in the one mode that gets
 * shown to people in rooms with no database.
 *
 * Annotated rather than inferred so a regenerated fixture on the other regime
 * still compiles and still labels itself correctly.
 */
const DEMO_RELIEF: ReliefRegime = DEMO_PAYSLIP_BASIS.schedule.relief;

/**
 * Whether the illustrative figures still describe this company.
 *
 * They were generated on one set of rates, recorded in `DEMO_PAYSLIP_BASIS`.
 * Change the salary split or a pension rate in demo mode and they describe a
 * company that is no longer this one — so the run withholds them and says why,
 * rather than printing figures that contradict the settings screen.
 *
 * `workingDaysPerMonth` is deliberately not compared: the demo run applies no
 * unpaid days, so the divisor cannot move any figure in the fixture. The
 * exception rules are not compared either — they decide what stops a run, not
 * what anybody is paid.
 */
function settingsMatchFixture(settings: PayrollSettings): boolean {
  const basis = DEMO_PAYSLIP_BASIS.settings;
  const sameBasis =
    settings.pension.basis.length === basis.pension.basis.length &&
    basis.pension.basis.every((component) =>
      settings.pension.basis.includes(component),
    );

  return (
    settings.salarySplit.basic === basis.salarySplit.basic &&
    settings.salarySplit.housing === basis.salarySplit.housing &&
    settings.salarySplit.transport === basis.salarySplit.transport &&
    /* The three deduction switches. A fixture generated with PAYE on cannot
       describe a company that has switched it off — every figure below the gross
       line would be a deduction the settings screen says does not happen — so the
       run refuses rather than printing figures that contradict it. */
    settings.paye.enabled === basis.paye.enabled &&
    settings.pension.enabled === basis.pension.enabled &&
    settings.pension.employeeRate === basis.pension.employeeRate &&
    settings.pension.employerRate === basis.pension.employerRate &&
    sameBasis &&
    settings.nhf.enabled === basis.nhf.enabled &&
    settings.nhf.rate === basis.nhf.rate &&
    settings.nhf.basis === basis.nhf.basis
  );
}

/**
 * One demo payslip, in whole kobo, or null.
 *
 * Every statutory figure is read from the fixture — generated by the API's
 * engine, never recomputed here. The only arithmetic is the post-tax deduction,
 * and it is the one piece that needs none: a loan instalment comes off net after
 * PAYE, pension and NHF are settled, so take-home falls by exactly its own
 * amount. Capped at what is there, with the shortfall reported, because a month
 * of unpaid leave is enough to make an instalment unrecoverable and the loan
 * carries the remainder rather than the payslip going negative.
 *
 * Null when the fixture has no row for this salary. The caller turns that into a
 * BLOCKER naming the person; it never becomes a zero, because a zero on a
 * payslip is a claim and this is an absence.
 */
function demoPayslip(
  period: string,
  person: PayrollEmployee,
  figures: DemoPayslipFigures,
): { slip: Payslip; unrecoveredKobo: number } {
  const scheduled = SCHEDULED_DEDUCTIONS.get(person.id);

  const requestedKobo = kobo(scheduled?.amount ?? 0);
  const takenKobo = Math.min(requestedKobo, Math.max(0, figures.netKobo));
  const unrecoveredKobo = requestedKobo - takenKobo;

  const lines: PayslipLine[] = [];
  if (requestedKobo > 0 && scheduled) {
    lines.push({
      id: `${person.id}-deduction`,
      kind: "DEDUCTION",
      label: scheduled.label,
      /* The full instalment, not what fitted. `reconcile.ts` allows the line to
         exceed what was taken precisely so the carried remainder stays visible
         instead of quietly vanishing off the slip. */
      amountKobo: requestedKobo,
      taxable: false,
    });
  }
  lines.push({
    id: `${person.id}-employer-pension`,
    kind: "EMPLOYER_CONTRIBUTION",
    label: "Employer pension",
    amountKobo: figures.pensionEmployerKobo,
    taxable: false,
  });

  return {
    unrecoveredKobo,
    slip: {
      id: demoPayslipId(period, person.id),
      employeeId: person.id,
      employeeNo: person.id.toUpperCase(),
      name: person.name,
      grossKobo: figures.grossKobo,
      basicKobo: figures.basicKobo,
      housingKobo: figures.housingKobo,
      transportKobo: figures.transportKobo,
      pensionEmployeeKobo: figures.pensionEmployeeKobo,
      pensionEmployerKobo: figures.pensionEmployerKobo,
      nhfKobo: figures.nhfKobo,
      taxableIncomeKobo: figures.taxableMonthlyKobo,
      reliefKobo: figures.reliefMonthlyKobo,
      relief: DEMO_RELIEF,
      payeKobo: figures.payeKobo,
      /* Demo payroll is always the fixture's own figures — see the module
         header on why an override cannot exist here without a second engine
         in the browser. */
      payeOverridden: false,
      payeOverrideReason: null,
      otherDeductionsKobo: takenKobo,
      netKobo: figures.netKobo - takenKobo,
      unpaidDays: 0,
      proratedDeductionKobo: 0,
      publishedAt: null,
      emailedAt: null,
      viewedAt: null,
      lines,
    },
  };
}

/**
 * The invariant check, in demo mode.
 *
 * The same identities `approvehr-api/src/modules/payroll/reconcile.ts` asserts,
 * because the gate has to be real in both modes. A demo that renders whatever
 * the arithmetic produced would be demonstrating the incumbent's bug — an
 * audit of the live competitor found a run paying out ₦1.47m more than it cost,
 * displayed without complaint, and the failure was not the arithmetic but that
 * nothing between it and the screen ever asked whether it added up.
 *
 * Exact integer equality, no tolerance. A tolerance is a decision that being
 * slightly wrong is acceptable, and on a payment file it is not.
 */
function reconcileDemo(slips: Payslip[], totals: RunTotalsKobo): Discrepancy[] {
  const found: Discrepancy[] = [];
  const money = (k: number) =>
    (k / 100).toLocaleString("en-NG", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    });

  for (const slip of slips) {
    const taken =
      slip.pensionEmployeeKobo +
      slip.nhfKobo +
      slip.payeKobo +
      slip.otherDeductionsKobo;
    if (slip.netKobo + taken !== slip.grossKobo) {
      found.push({
        code: "net_does_not_reconcile",
        employeeId: slip.employeeId,
        message:
          `Net pay plus deductions comes to ₦${money(slip.netKobo + taken)}, ` +
          `but gross is ₦${money(slip.grossKobo)}.`,
        expectedKobo: slip.grossKobo,
        actualKobo: slip.netKobo + taken,
      });
    }
    if (slip.netKobo > slip.grossKobo) {
      found.push({
        code: "net_exceeds_gross",
        employeeId: slip.employeeId,
        message:
          `Net pay ₦${money(slip.netKobo)} is more than gross ` +
          `₦${money(slip.grossKobo)}. This cannot be right.`,
        expectedKobo: slip.grossKobo,
        actualKobo: slip.netKobo,
      });
    }
    const split = slip.basicKobo + slip.housingKobo + slip.transportKobo;
    if (split !== slip.grossKobo) {
      found.push({
        code: "split_does_not_sum",
        employeeId: slip.employeeId,
        message:
          `Basic plus housing plus transport is ₦${money(split)}, ` +
          `contractual pay is ₦${money(slip.grossKobo)}.`,
        expectedKobo: slip.grossKobo,
        actualKobo: split,
      });
    }
  }

  const fields: [string, number, number][] = [
    ["gross", slips.reduce((t, s) => t + s.grossKobo, 0), totals.grossKobo],
    ["net", slips.reduce((t, s) => t + s.netKobo, 0), totals.netKobo],
    ["PAYE", slips.reduce((t, s) => t + s.payeKobo, 0), totals.payeKobo],
  ];
  for (const [label, expected, actual] of fields) {
    if (expected !== actual) {
      found.push({
        code: "total_does_not_match_payslips",
        message:
          `Total ${label} is ₦${money(actual)} but the payslips add to ` +
          `₦${money(expected)}.`,
        expectedKobo: expected,
        actualKobo: actual,
      });
    }
  }

  return found;
}

type RunTotalsKobo = {
  grossKobo: number;
  netKobo: number;
  payeKobo: number;
  pensionEmployeeKobo: number;
  pensionEmployerKobo: number;
  nhfKobo: number;
};

function totalsOf(slips: Payslip[]): RunTotalsKobo {
  return slips.reduce<RunTotalsKobo>(
    (t, s) => ({
      grossKobo: t.grossKobo + s.grossKobo,
      netKobo: t.netKobo + s.netKobo,
      payeKobo: t.payeKobo + s.payeKobo,
      pensionEmployeeKobo: t.pensionEmployeeKobo + s.pensionEmployeeKobo,
      pensionEmployerKobo: t.pensionEmployerKobo + s.pensionEmployerKobo,
      nhfKobo: t.nhfKobo + s.nhfKobo,
    }),
    {
      grossKobo: 0,
      netKobo: 0,
      payeKobo: 0,
      pensionEmployeeKobo: 0,
      pensionEmployerKobo: 0,
      nhfKobo: 0,
    },
  );
}

/**
 * Demo exceptions, using the API's own codes and severities.
 *
 * Deliberately not `findExceptions` from the frontend engine: that marks a
 * missing pension PIN as *blocking*, and the API treats it as a warning. The
 * demo has to teach what the product actually does, so where the two disagree
 * the API wins and the codes match so a fix link resolves the same way.
 */
function demoExceptions(
  people: PayrollEmployee[],
  slips: Map<string, { slip: Payslip; unrecoveredKobo: number }>,
  settings: PayrollSettings,
  excluded: Map<string, DemoExclusion>,
): RunException[] {
  const out: RunException[] = [];
  const push = (
    severity: RunException["severity"],
    code: string,
    employeeId: string | null,
    message: string,
  ) =>
    out.push({
      id: `${code}-${employeeId ?? "run"}`,
      employeeId,
      severity,
      code,
      message,
    });

  /* Said once, at the top, and never implied away. Every figure on this run is
     output the API's engine produced for the demo salaries — not a live
     calculation, and not one this browser could perform. */
  push(
    "WARNING",
    "demo_illustrative_figures",
    null,
    `These figures are illustrative. They were computed by the payroll engine ` +
      `on the API for ${DEMO_PAYSLIP_BASIS.period} on the demo salaries and are ` +
      `fixed; a real run computes every one of them live. Nothing in this ` +
      `browser calculates PAYE.`,
  );

  /* Settings that no longer match what the figures were generated on. One
     BLOCKER for the run, because every payslip below is affected and repeating
     it per person would bury the reason. */
  if (!settingsMatchFixture(settings)) {
    push(
      "BLOCKER",
      "demo_settings_changed",
      null,
      "These payroll settings are not the ones the demo's illustrative figures " +
        "were computed on, so they no longer describe what this company pays. " +
        "Reset the payroll settings to their defaults, or start the API to see " +
        "figures computed on your own settings.",
    );
  }

  for (const person of people) {
    /**
     * Deliberately left off, so nothing else about them is raised.
     *
     * A WARNING carrying the reason, the decider and the date — the same code
     * and severity the API uses, so a screen written against one works against
     * the other. Not a silent omission: the run has to be able to answer "why
     * was Grace not paid in August?" from its own list of exceptions.
     */
    const left = excluded.get(person.id);
    if (left) {
      const decidedBy = left.decidedBy ? ` by ${left.decidedBy}` : "";
      push(
        "WARNING",
        "excluded_from_payroll",
        person.id,
        /* The trailing full stop is stripped inside the quotes: it would
           double up with the one closing this sentence. Same as the API. */
        `${person.name} is not being paid this period — ` +
          `"${left.reason.replace(/\.$/, "")}". ` +
          `Excluded${decidedBy} on ${left.excludedAt.slice(0, 10)}. They have no ` +
          `payslip on this run and nothing is owed to them by it. They are back ` +
          `on the next period's payroll automatically.`,
      );
      continue;
    }

    const entry = slips.get(person.id);
    if (!entry) {
      /* No illustrative figures for this salary. A blocker rather than a
         silent omission: they are on the payroll and their payslip is missing,
         which is exactly the kind of thing a run must not swallow. */
      push(
        "BLOCKER",
        "demo_no_figures",
        person.id,
        `${person.name} has no payslip in this run. The demo holds illustrative ` +
          `figures only for its own salaries, and theirs is not one of them — ` +
          `statutory deductions are computed by the API and there is no second ` +
          `copy of that arithmetic here. Start the API to pay them.`,
      );
      continue;
    }

    if (settings.exceptions.requireBankAccount && !person.bankAccount) {
      push(
        "BLOCKER",
        "missing_bank_account",
        person.id,
        `${person.name} has no account number. They cannot be paid. ` +
          `Add one, or exclude them from this payroll with a reason.`,
      );
    }
    if (
      settings.exceptions.requirePensionPin &&
      settings.pension.enabled &&
      !person.pensionPin
    ) {
      push(
        "WARNING",
        "missing_pension_pin",
        person.id,
        `${person.name} has no pension PIN. The pension schedule will be incomplete.`,
      );
    }
    if (settings.exceptions.blockNegativeNet && entry.slip.netKobo <= 0) {
      push(
        "BLOCKER",
        "negative_net",
        person.id,
        `${person.name} would be paid nothing this month. Check their deductions.`,
      );
    }
    if (entry.unrecoveredKobo > 0) {
      push(
        "WARNING",
        "deduction_carried",
        person.id,
        `${person.name} earned less than their deductions this month. ` +
          `₦${(entry.unrecoveredKobo / 100).toLocaleString("en-NG", {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
          })} carries forward.`,
      );
    }

    const before = PREVIOUS_NET.get(person.id);
    if (before && before > 0 && !person.joinedThisPeriod) {
      const change = (entry.slip.netKobo / 100 - before) / before;
      if (Math.abs(change) >= settings.exceptions.netSwingThreshold) {
        push(
          "WARNING",
          "net_swing",
          person.id,
          `${person.name}'s net pay is ${change > 0 ? "up" : "down"} ` +
            `${Math.abs(Math.round(change * 100))}% on last month. Confirm that is intended.`,
        );
      }
    }
    if (person.leftThisPeriod) {
      /* `exit_final_pay`, which is the code the API emits for this exact case —
         `leftThisPeriod` is an end date inside the period, and that is
         `exitExceptionsFor`'s `finalMonth` branch in
         `approvehr-api/src/modules/offboarding/service.ts`.

         It used to be `"leaver"`, which was wrong twice over. It is a word this
         product does not use — the vocabulary is "exit" — and no API code has
         ever been called that, so `fixFor()` in `lib/api/payroll.ts` switches on
         a string the connected product never sends. A demo teaching a code that
         does not exist is the one thing this function's header says it must not
         do. */
      push(
        "WARNING",
        "exit_final_pay",
        person.id,
        `${person.name} leaves this period. This is their last payslip — check ` +
          `the final figure and any loan balance before you approve, because ` +
          `there is no next month to correct it in.`,
      );
    }
  }

  return out;
}

/**
 * The settings a demo run computes against.
 *
 * `usePayrollSettings` is localStorage and holds the rates. The **three
 * deduction switches** are not its to answer: the setup wizard writes them into
 * the features store offline, and `GET /payroll/settings` owns them connected.
 * Merged here so one object describes what this company pays, and so
 * `settingsMatchFixture` sees a switched-off deduction as a change like any
 * other and refuses the run.
 *
 * Without this the demo would contradict itself: the wizard would record "we do
 * not deduct PAYE" and the payroll run would keep showing PAYE on every payslip.
 */
function useDemoPayrollSettings(): PayrollSettings {
  const { settings } = usePayrollSettings();
  const answers = useDemoDeductions();
  return useMemo(
    () =>
      answers === null
        ? settings
        : {
            ...settings,
            paye: { enabled: answers.payeEnabled },
            pension: { ...settings.pension, enabled: answers.pensionEnabled },
            nhf: { ...settings.nhf, enabled: answers.nhfEnabled },
          },
    [settings, answers],
  );
}

/**
 * Builds a whole demo run from the live directory.
 *
 * Two people can be in the directory and not in the run: somebody whose salary
 * the fixture has no row for, and everybody at once when the settings have moved
 * away from what the fixture was generated on. Both are BLOCKERs naming the
 * reason — the headcount is the number of payslips there actually are, because a
 * total that counts a payslip it does not have is the incumbent's bug.
 */
function buildDemoRun(
  record: DemoRunRecord,
  people: PayrollEmployee[],
  settings: PayrollSettings,
): PayrollRunDetail {
  const usable = settingsMatchFixture(settings);

  /**
   * The population, split, exactly as `prepare` splits it on the API.
   *
   * `people` is everybody the period covers. Only the ones nobody has excluded
   * get a payslip — and only they raise an exception about their own record,
   * because a blocker about the account number of somebody who is not being paid
   * is a blocker nobody can act on and it would hold every other salary.
   *
   * Intersected with the period's population, so an exclusion recorded for
   * somebody the period no longer covers counts for nothing. The record survives;
   * it just does not claim this run left somebody off who was never on it.
   */
  const excluded = new Map(
    exclusionsOf(record)
      .filter((row) => people.some((person) => person.id === row.employeeId))
      .map((row) => [row.employeeId, row] as const),
  );
  const payable = people.filter((person) => !excluded.has(person.id));

  const computed = new Map(
    payable.flatMap((person) => {
      /* No agreed pay, no payslip — the same rule the API's `prepare` follows,
         where it raises `missing_pay` naming them. This map already omits
         anybody it has no figures for, so the person simply is not on the run. */
      const figures =
        usable && person.grossMonthly !== null
          ? payslipFiguresFor(kobo(person.grossMonthly))
          : null;
      return figures
        ? [[person.id, demoPayslip(record.period, person, figures)] as const]
        : [];
    }),
  );
  const slips = [...computed.values()].map((c) => c.slip);
  const totals = totalsOf(slips);

  const exclusions: RunExclusion[] = [...excluded.values()].flatMap((row) => {
    const person = people.find((p) => p.id === row.employeeId);
    return person
      ? [
          {
            id: `${record.period}-${row.employeeId}`,
            employeeId: row.employeeId,
            employeeNo: row.employeeId.toUpperCase(),
            name: person.name,
            reason: row.reason,
            decidedBy: row.decidedBy,
            excludedAt: row.excludedAt,
          },
        ]
      : [];
  });

  return {
    id: demoRunId(record.period),
    period: record.period,
    payDate: record.payDate,
    status: record.status,
    label: record.label,
    employeeCount: slips.length,
    excludedCount: excluded.size,
    grossKobo: totals.grossKobo,
    netKobo: totals.netKobo,
    payeKobo: totals.payeKobo,
    pensionEmployeeKobo: totals.pensionEmployeeKobo,
    pensionEmployerKobo: totals.pensionEmployerKobo,
    nhfKobo: totals.nhfKobo,
    totalCostKobo: totals.grossKobo + totals.pensionEmployerKobo,
    /* The demo payslips are fixed illustrative rows generated by the API's
       engine on its defaults, which deduct all three. A local switch cannot move
       them, so the demo run must not claim otherwise — `/settings/payroll` says
       the same thing beside the switches. */
    operates: { paye: "DEDUCTED", pension: "DEDUCTED", nhf: "DEDUCTED" },
    preparedAt: record.preparedAt,
    approvedAt: record.approvedAt,
    paidAt: null,
    settingsFrozen: false,
    payslips: slips,
    exceptions: demoExceptions(people, computed, settings, excluded),
    exclusions,
    /* Entering PAYE by hand needs the same engine the figures themselves
       came from, so it is refused in demo mode outright — see
       `usePayrollActions().setTaxOverride`. Nothing here can ever be
       overridden, so the list is always empty. */
    taxOverrides: [],
  };
}

/**
 * The `PreparedRun` shape, from a demo run that has just been built.
 *
 * One place, because three demo actions answer with it — prepare, exclude and
 * put back — and each one has to report the same figures the screen will read
 * back out of the run itself. `excluded` is beside `headcount` rather than
 * inside it: a caller has to be able to say "9 of 10 — 1 excluded".
 */
const preparedFrom = (detail: PayrollRunDetail): PreparedRun => ({
  runId: detail.id,
  headcount: detail.employeeCount,
  excluded: detail.excludedCount,
  discrepancies: reconcileDemo(detail.payslips, totalsOf(detail.payslips)),
  blockers: detail.exceptions.filter((e) => e.severity === "BLOCKER").length,
  warnings: detail.exceptions.filter((e) => e.severity === "WARNING").length,
});

/** The frozen snapshot wins whenever there is one. That is the one-way door. */
const resolveDemoRun = (
  record: DemoRunRecord,
  people: PayrollEmployee[],
  settings: PayrollSettings,
): PayrollRunDetail => record.frozen ?? buildDemoRun(record, people, settings);

const summarise = (detail: PayrollRunDetail): PayrollRun => {
  const { payslips, exceptions, exclusions, ...run } = detail;
  void payslips;
  void exceptions;
  void exclusions;
  return run;
};

/* ------------------------------------------------------------------- hooks */

/**
 * Everything a screen needs about who is being read from.
 *
 * Bundled rather than each hook re-deriving it, because the demo run depends on
 * three live sources — the directory, the settings, and the persisted run list
 * — and reading them in one place keeps every hook's demo answer identical.
 */
function useDemoContext() {
  const { directory } = useEmployeeStore();
  const settings = useDemoPayrollSettings();
  const state = useDemoRuns();
  const people = useMemo(() => runPeopleFrom(directory), [directory]);
  const details = useMemo(
    () =>
      [...state.runs]
        .sort((a, b) => b.period.localeCompare(a.period))
        .map((record) => resolveDemoRun(record, people, settings)),
    [state.runs, people, settings],
  );
  return { details, records: state.runs };
}

export type RunsState = {
  runs: PayrollRun[];
  total: number;
  loading: boolean;
  error: ApiError | null;
  connected: boolean;
  reload: () => void;
};

/** Every run, newest period first. */
export function usePayrollRuns(): RunsState {
  const { isConnected } = useSession();
  const demo = useDemoContext();

  const [state, setState] = useState<{
    runs: PayrollRun[];
    total: number;
    loading: boolean;
    error: ApiError | null;
  }>({ runs: [], total: 0, loading: isConnected, error: null });

  const load = useCallback(async () => {
    if (!isConnected) return;
    setState((s) => ({ ...s, loading: true, error: null }));
    try {
      const result = await payrollApi.runs();
      setState({
        runs: result.runs,
        total: result.total,
        loading: false,
        error: null,
      });
    } catch (error) {
      setState((s) => ({
        ...s,
        loading: false,
        error: error instanceof ApiError ? error : null,
      }));
    }
  }, [isConnected]);

  /* Re-ask when somebody comes back to the window. Not in the key below,
     so the answer is replaced without the screen flashing a skeleton. */
  const revalidation = useRevalidation();
  useEffect(() => {
    void load();
  }, [load, revalidation]);

  if (!isConnected) {
    const runs = demo.details.map(summarise);
    return {
      runs,
      total: runs.length,
      loading: false,
      error: null,
      connected: false,
      reload: () => {},
    };
  }

  return { ...state, connected: true, reload: load };
}

export type RunState = {
  run: PayrollRunDetail | null;
  loading: boolean;
  error: ApiError | null;
  connected: boolean;
  /** No such run. Distinct from an error: there is nothing to retry. */
  notFound: boolean;
  reload: () => void;
};

/**
 * One run in full, with its payslips and open exceptions.
 *
 * Kept as `{ id, nonce, detail }` rather than a bare detail so the result
 * carries the request it belongs to. `loading` is then derived during render
 * instead of tracked, which means there is nothing to clear when `id` changes
 * and no window where the previous run's figures are shown as though they were
 * this one's. Clearing it in an effect would be a setState in an effect body.
 */
export function usePayrollRun(id: string | null): RunState {
  const { isConnected } = useSession();
  const demo = useDemoContext();
  const [nonce, setNonce] = useState(0);
  const [fetched, setFetched] = useState<{
    id: string;
    nonce: number;
    detail: PayrollRunDetail | null;
    error: ApiError | null;
  } | null>(null);

  const active = isConnected && Boolean(id);

  /* Re-ask when somebody comes back to the window. Not in the key below,
     so the answer is replaced without the screen flashing a skeleton. */
  const revalidation = useRevalidation();
  useEffect(() => {
    if (!active || !id) return;
    let cancelled = false;
    const controller = new AbortController();
    void (async () => {
      try {
        const detail = await payrollApi.run(id, controller.signal);
        if (!cancelled) setFetched({ id, nonce, detail, error: null });
      } catch (error) {
        if (error instanceof DOMException && error.name === "AbortError")
          return;
        if (!cancelled) {
          setFetched({
            id,
            nonce,
            detail: null,
            error: error instanceof ApiError ? error : null,
          });
        }
      }
    })();
    return () => {
      cancelled = true;
      controller.abort();
    };
  }, [active, id, nonce, revalidation]);

  const reload = useCallback(() => setNonce((n) => n + 1), []);

  if (!isConnected) {
    const run = id ? (demo.details.find((d) => d.id === id) ?? null) : null;
    return {
      run,
      loading: false,
      error: null,
      connected: false,
      notFound: Boolean(id) && run === null,
      reload: () => {},
    };
  }

  const matched =
    active && fetched !== null && fetched.id === id && fetched.nonce === nonce;
  return {
    run: matched ? fetched.detail : null,
    loading: active && !matched,
    error: matched ? fetched.error : null,
    connected: true,
    notFound: matched && fetched.error?.status === 404,
    reload,
  };
}

/**
 * One run's payslips, filtered, sorted and paged by the API.
 *
 * ## Why the distribution table stopped reading `usePayrollRun`
 *
 * `usePayrollRun` returns the run with **every** payslip nested. The payslip
 * index took that array, sorted it, filtered it and counted it, and put three
 * figures above the table: total, not sent, opened. For a company of two thousand
 * that response is megabytes, the counts describe the array rather than the
 * payroll, and the sort is over whatever the API happened to send.
 *
 * `GET /payroll/runs/:id/payslips` answers the counts alongside the page, so
 * "Not sent: 1,974" is a `count` query rather than a `filter().length`.
 *
 * ## Demo mode pages and counts the fixture the same way
 *
 * The demo run holds its payslips in the persisted record, so filtering them
 * locally is not a lie — there is no larger set behind them. What it must still
 * do is **count before it cuts**, which is the habit the connected path depends
 * on: a demo that reported the page length would let a screen ship a bug that
 * only appears against a database.
 */
export type RunPayslipsState = {
  payslips: Payslip[];
  /** The server's count under this filter. `undefined` until it answers. */
  total: number | undefined;
  /** How many are in each delivery state across the whole run, from the server. */
  counts: PayslipCounts | undefined;
  loading: boolean;
  error: ApiError | null;
  connected: boolean;
};

/** Which of the three delivery states a payslip is in. */
export const deliveryOf = (slip: Payslip): PayslipDelivery =>
  slip.viewedAt ? "opened" : slip.emailedAt ? "sent" : "not_sent";

export function useRunPayslips(
  runId: string | null,
  params: PayslipListParams = {},
): RunPayslipsState {
  const { isConnected } = useSession();
  const demo = useDemoContext();

  const key = JSON.stringify(params);
  const active = isConnected && Boolean(runId);

  const [fetched, setFetched] = useState<{
    runId: string;
    key: string;
    page: PayslipPage | null;
    error: ApiError | null;
  } | null>(null);

  /* Re-ask when somebody comes back to the window. Not in the key below,
     so the answer is replaced without the screen flashing a skeleton. */
  const revalidation = useRevalidation();
  useEffect(() => {
    if (!active || !runId) return;
    let cancelled = false;
    const controller = new AbortController();

    void (async () => {
      try {
        const page = await payrollApi.payslips(
          runId,
          JSON.parse(key) as PayslipListParams,
          controller.signal,
        );
        if (!cancelled) setFetched({ runId, key, page, error: null });
      } catch (error) {
        if (error instanceof DOMException && error.name === "AbortError")
          return;
        if (!cancelled) {
          setFetched({
            runId,
            key,
            page: null,
            error: error instanceof ApiError ? error : null,
          });
        }
      }
    })();

    return () => {
      cancelled = true;
      controller.abort();
    };
  }, [active, runId, key, revalidation]);

  /* The demo answer, computed in a `useMemo` that touches no state — the shape
     `lib/store/shifts.ts` establishes and every store in this app follows. */
  const local = useMemo(() => {
    if (isConnected) return null;
    const run = runId
      ? demo.details.find((detail) => detail.id === runId)
      : null;
    if (!run) {
      return {
        payslips: [] as Payslip[],
        total: 0,
        counts: { notSent: 0, sent: 0, opened: 0 },
      };
    }
    const parsed = JSON.parse(key) as PayslipListParams;

    const searched = parsed.q
      ? run.payslips.filter((slip) =>
          [slip.name, slip.employeeNo].some((field) =>
            field.toLowerCase().includes(parsed.q!.toLowerCase()),
          ),
        )
      : run.payslips;

    /* The three counts are over the searched set and **not** the delivery
       filter, exactly as the API computes them: they are the counts beside the
       filter, so they have to say what is behind the option you are not on. */
    const counts = {
      notSent: searched.filter((s) => deliveryOf(s) === "not_sent").length,
      sent: searched.filter((s) => deliveryOf(s) === "sent").length,
      opened: searched.filter((s) => deliveryOf(s) === "opened").length,
    };

    const matched = parsed.delivery
      ? searched.filter((slip) => deliveryOf(slip) === parsed.delivery)
      : searched;

    const sorted = sortPayslips(matched, parsed);
    const size = parsed.pageSize ?? 25;
    const start = ((parsed.page ?? 1) - 1) * size;

    return {
      payslips: sorted.slice(start, start + size),
      total: matched.length,
      counts,
    };
  }, [isConnected, runId, key, demo.details]);

  if (local) {
    return { ...local, loading: false, error: null, connected: false };
  }

  const matched =
    active &&
    fetched !== null &&
    fetched.runId === runId &&
    fetched.key === key;

  return {
    payslips: matched ? (fetched.page?.payslips ?? []) : [],
    total: matched ? fetched.page?.total : undefined,
    counts: matched ? fetched.page?.counts : undefined,
    loading: active && !matched,
    error: matched ? fetched.error : null,
    connected: true,
  };
}

/**
 * The demo's copy of the API's payslip order — **with the tiebreaker**.
 *
 * `id` last for the same reason the API does it. Sorting two thousand payslips by
 * net pay, where every intern ties on the same figure, otherwise puts somebody on
 * two pages and somebody else on none.
 */
function sortPayslips(rows: Payslip[], params: PayslipListParams): Payslip[] {
  const dir = params.order === "desc" ? -1 : 1;

  const value = (slip: Payslip): string | number => {
    switch (params.sort) {
      case "employeeNo":
        return slip.employeeNo.toLowerCase();
      case "gross":
        return slip.grossKobo;
      case "net":
        return slip.netKobo;
      case "paye":
        return slip.payeKobo;
      case "emailedAt":
        return slip.emailedAt ?? "";
      case "viewedAt":
        return slip.viewedAt ?? "";
      default:
        return slip.name.toLowerCase();
    }
  };

  if (!params.sort) {
    /* No sort asked for: the queue. Not-yet-emailed first, then by name. */
    return [...rows].sort(
      (a, b) =>
        DELIVERY_RANK[deliveryOf(a)] - DELIVERY_RANK[deliveryOf(b)] ||
        a.name.localeCompare(b.name) ||
        a.id.localeCompare(b.id),
    );
  }

  return [...rows].sort((a, b) => {
    const left = value(a);
    const right = value(b);
    if (left < right) return -dir;
    if (left > right) return dir;
    return a.id < b.id ? -dir : a.id > b.id ? dir : 0;
  });
}

export type OwnPayslipsState = {
  payslips: OwnPayslip[];
  /** The server's count. `undefined` until it answers. Always `payslips.length` in demo mode — there is no larger set behind the fixture. */
  total: number | undefined;
  loading: boolean;
  error: ApiError | null;
  connected: boolean;
};

/**
 * One employee's own payslip history, across every run — the self-service
 * counterpart to `useRunPayslips`. `null` id means "not known yet" (a session
 * still loading its own employee id), not "no payslips".
 */
export function useMyPayslips(employeeId: string | null): OwnPayslipsState {
  const { isConnected } = useSession();
  const demo = useDemoContext();

  const active = isConnected && Boolean(employeeId);

  const [fetched, setFetched] = useState<{
    employeeId: string;
    page: { payslips: OwnPayslip[]; total: number } | null;
    error: ApiError | null;
  } | null>(null);

  /* Re-ask when somebody comes back to the window. Not in the key below,
     so the answer is replaced without the screen flashing a skeleton. */
  const revalidation = useRevalidation();
  useEffect(() => {
    if (!active || !employeeId) return;
    let cancelled = false;
    const controller = new AbortController();

    void (async () => {
      try {
        const page = await payrollApi.employeePayslips(
          employeeId,
          { pageSize: 50 },
          controller.signal,
        );
        if (!cancelled) setFetched({ employeeId, page, error: null });
      } catch (error) {
        if (error instanceof DOMException && error.name === "AbortError")
          return;
        if (!cancelled) {
          setFetched({
            employeeId,
            page: null,
            error: error instanceof ApiError ? error : null,
          });
        }
      }
    })();

    return () => {
      cancelled = true;
      controller.abort();
    };
  }, [active, employeeId, revalidation]);

  /* Same shape as `useRunPayslips`'s demo branch: a `useMemo` touching no
     state. Every demo run already carries its payslips, so this is a filter
     across all of them rather than a second fixture to keep in step. */
  const local = useMemo(() => {
    if (isConnected || !employeeId) return null;
    const mine = demo.details.flatMap((run) =>
      run.payslips
        .filter((slip) => slip.employeeId === employeeId)
        .map((slip) => ({
          ...slip,
          run: {
            id: run.id,
            period: run.period,
            payDate: run.payDate,
            status: run.status,
          },
        })),
    );
    return { payslips: mine, total: mine.length };
  }, [isConnected, employeeId, demo.details]);

  if (local) {
    return { ...local, loading: false, error: null, connected: false };
  }

  const matched =
    active && fetched !== null && fetched.employeeId === employeeId;

  return {
    payslips: matched ? (fetched.page?.payslips ?? []) : [],
    total: matched ? fetched.page?.total : undefined,
    loading: active && !matched,
    error: matched ? fetched.error : null,
    connected: true,
  };
}

/** What needs a human, first. */
const DELIVERY_RANK: Record<PayslipDelivery, number> = {
  not_sent: 0,
  sent: 1,
  opened: 2,
};

/**
 * Prepare, approve, cancel, exclude, put back.
 *
 * Each one refuses in demo mode only where the demo genuinely cannot do it,
 * and all of them do work locally — preparing a period, excluding the one person
 * whose record is incomplete, and approving it is the sequence the demo most
 * needs to be able to show.
 */
export function usePayrollActions() {
  const { isConnected, displayName } = useSession();
  const { directory } = useEmployeeStore();
  const settings = useDemoPayrollSettings();
  const people = useMemo(() => runPeopleFrom(directory), [directory]);

  const prepare = useCallback(
    async (input: {
      period: string;
      payDate: string;
      label?: string;
    }): Promise<PreparedRun> => {
      if (isConnected) return payrollApi.prepare(input);

      const state = demoStore.current();
      const existing = state.runs.find((r) => r.period === input.period);
      if (
        existing &&
        (existing.status === "APPROVED" || existing.status === "PAID")
      ) {
        throw new ApiError(
          409,
          "conflict",
          `The ${input.period} run is already approved. Cancel it before preparing that period again.`,
        );
      }
      if (people.length === 0) {
        throw new ApiError(
          422,
          "unprocessable",
          "Nobody is on the payroll for this period. Add employees first.",
        );
      }

      const record: DemoRunRecord = {
        period: input.period,
        payDate: input.payDate,
        label: input.label ?? null,
        status: "IN_REVIEW",
        preparedAt: new Date().toISOString(),
        approvedAt: null,
        /**
         * Carried over, never rebuilt.
         *
         * Preparing replaces the payslips and the exception list wholesale — on
         * the API and here. If it took the exclusions with them, excluding
         * somebody and pressing Calculate again would resurrect the blocker they
         * were excluded for and the loop would never end.
         */
        exclusions: existing ? exclusionsOf(existing) : [],
        frozen: null,
      };
      demoStore.commit({
        runs: [...state.runs.filter((r) => r.period !== input.period), record],
      });

      return preparedFrom(buildDemoRun(record, people, settings));
    },
    [isConnected, people, settings],
  );

  const approve = useCallback(
    async (runId: string): Promise<ApprovedRun> => {
      if (isConnected) return payrollApi.approve(runId);

      const state = demoStore.current();
      const record = state.runs.find((r) => demoRunId(r.period) === runId);
      if (!record) throw new ApiError(404, "not_found", "No such payroll run.");
      if (record.status === "APPROVED" || record.status === "PAID") {
        throw new ApiError(409, "conflict", "That run is already approved.");
      }

      const detail = buildDemoRun(record, people, settings);
      const blockers = detail.exceptions.filter(
        (e) => e.severity === "BLOCKER",
      );
      if (blockers.length > 0) {
        throw new ApiError(
          422,
          "unprocessable",
          `This run cannot be approved yet. ${blockers.map((b) => b.message).join(" ")}`,
        );
      }

      const approvedAt = new Date().toISOString();
      /* Frozen here and nowhere else. After this the figures no longer move
         when the directory does — which is the whole point of approving. */
      const frozen: PayrollRunDetail = {
        ...detail,
        status: "APPROVED",
        approvedAt,
        settingsFrozen: true,
        exceptions: detail.exceptions.filter((e) => e.severity === "WARNING"),
      };
      demoStore.commit({
        runs: state.runs.map((r) =>
          r.period === record.period
            ? { ...r, status: "APPROVED" as const, approvedAt, frozen }
            : r,
        ),
      });

      const settledLoans = detail.payslips.filter((p) =>
        p.lines.some((l) => l.kind === "DEDUCTION" && !l.taxable),
      ).length;
      return {
        id: runId,
        settled: { loans: settledLoans, claims: 0, overtime: 0 },
      };
    },
    [isConnected, people, settings],
  );

  const cancel = useCallback(
    async (runId: string): Promise<{ id: string }> => {
      if (isConnected) return payrollApi.cancel(runId);

      const state = demoStore.current();
      const record = state.runs.find((r) => demoRunId(r.period) === runId);
      if (!record) throw new ApiError(404, "not_found", "No such payroll run.");
      if (record.status === "PAID") {
        throw new ApiError(
          409,
          "conflict",
          "That run has been paid. A paid run is a record of money that moved and cannot be cancelled.",
        );
      }
      demoStore.commit({
        runs: state.runs.map((r) =>
          r.period === record.period
            ? { ...r, status: "CANCELLED" as const, frozen: null }
            : r,
        ),
      });
      return { id: runId };
    },
    [isConnected],
  );

  /**
   * Leaves somebody off this payroll, with the reason on the record.
   *
   * Rebuilds the period in both modes, and answers with the rebuilt figures —
   * because a run is a function of the directory and this run's exclusions, so
   * every total and both counts move the moment somebody is left off. A screen
   * that kept the old ones would show a payslip for somebody it says is not
   * being paid.
   */
  const exclude = useCallback(
    async (
      runId: string,
      input: { employeeId: string; reason: string },
    ): Promise<ExclusionChange> => {
      if (isConnected) return payrollApi.exclude(runId, input);

      const reason = input.reason.trim();
      if (reason.length < 4) {
        throw new ApiError(
          422,
          "unprocessable",
          "Say why they are not being paid this period. This is the only answer " +
            "anybody will have in a year's time.",
        );
      }

      const state = demoStore.current();
      const record = state.runs.find((r) => demoRunId(r.period) === runId);
      if (!record) throw new ApiError(404, "not_found", "No such payroll run.");
      if (record.status !== "DRAFT" && record.status !== "IN_REVIEW") {
        throw new ApiError(
          409,
          "conflict",
          `The ${record.period} payroll is ${record.status.toLowerCase()}. ` +
            "Who was on it is part of the record now and cannot be changed.",
        );
      }

      const person = people.find((p) => p.id === input.employeeId);
      if (!person) throw new ApiError(404, "not_found", "No such employee.");
      if (exclusionsOf(record).some((row) => row.employeeId === person.id)) {
        throw new ApiError(
          409,
          "conflict",
          `${person.name} is already excluded from the ${record.period} payroll. ` +
            "Put them back on it first if the reason has changed.",
        );
      }

      const excludedAt = new Date().toISOString();
      const next: DemoRunRecord = {
        ...record,
        exclusions: [
          ...exclusionsOf(record),
          { employeeId: person.id, reason, decidedBy: displayName, excludedAt },
        ],
      };
      demoStore.commit({
        runs: state.runs.map((r) => (r.period === record.period ? next : r)),
      });

      return {
        employeeId: person.id,
        name: person.name,
        reason,
        excludedAt,
        run: preparedFrom(buildDemoRun(next, people, settings)),
      };
    },
    [isConnected, people, settings, displayName],
  );

  /**
   * Puts somebody back on this payroll.
   *
   * The record is removed rather than marked withdrawn: it described this run and
   * this run alone, and the run now carries the truth — they have a payslip
   * again. Whatever originally blocked them comes back with them if it was never
   * fixed, which is the point. This does not pay anybody; it stops them being
   * skipped.
   */
  const putBack = useCallback(
    async (runId: string, employeeId: string): Promise<ExclusionChange> => {
      if (isConnected) return payrollApi.putBack(runId, employeeId);

      const state = demoStore.current();
      const record = state.runs.find((r) => demoRunId(r.period) === runId);
      if (!record) throw new ApiError(404, "not_found", "No such payroll run.");
      if (record.status !== "DRAFT" && record.status !== "IN_REVIEW") {
        throw new ApiError(
          409,
          "conflict",
          `The ${record.period} payroll is ${record.status.toLowerCase()}. ` +
            "Who was on it is part of the record now and cannot be changed.",
        );
      }

      const kept = exclusionsOf(record).filter(
        (row) => row.employeeId !== employeeId,
      );
      if (kept.length === exclusionsOf(record).length) {
        throw new ApiError(
          404,
          "not_found",
          "That person is not excluded from this payroll.",
        );
      }

      const next: DemoRunRecord = { ...record, exclusions: kept };
      demoStore.commit({
        runs: state.runs.map((r) => (r.period === record.period ? next : r)),
      });

      const person = people.find((p) => p.id === employeeId);
      return {
        employeeId,
        name: person?.name ?? "That person",
        run: preparedFrom(buildDemoRun(next, people, settings)),
      };
    },
    [isConnected, people, settings],
  );

  /**
   * Enters somebody's PAYE by hand for this one payroll, in place of the
   * engine's own bands, and rebuilds the period.
   *
   * **Refuses outright in demo mode.** Every other write here can be
   * reproduced locally because it only decides who is on the run — the figures
   * themselves still come from the one real engine, generated once into the
   * demo fixture. Recomputing a payslip's net pay around a hand-typed PAYE
   * figure needs that same engine, and this repo has exactly one, in the API.
   * Reimplementing tax-band arithmetic here to make this button work offline
   * is the mistake `HANDOVER.md` spends a whole section warning against.
   */
  /**
   * Overtime hours entered by hand. Refuses offline for the same reason the
   * tax override does: hours typed here would be valued against a policy and a
   * salary the demo has no engine to apply, and a figure nobody computed is a
   * figure nobody can vouch for.
   */
  const setOvertimeOverride = useCallback(
    async (
      runId: string,
      input: {
        employeeId: string;
        hours: number;
        kind: OvertimeOverrideKind;
        reason: string;
      },
    ): Promise<OvertimeOverrideChange> => {
      if (isConnected) return payrollApi.setOvertimeOverride(runId, input);
      throw new ApiError(
        0,
        "offline",
        "Entering overtime by hand needs the API. The hourly rate comes from " +
          "the company's policy and the person's salary, and the demo has no " +
          "engine to apply them, so it will not pretend it has.",
      );
    },
    [isConnected],
  );

  const clearOvertimeOverride = useCallback(
    async (runId: string, employeeId: string): Promise<PreparedRun> => {
      if (isConnected) return payrollApi.clearOvertimeOverride(runId, employeeId);
      throw new ApiError(
        0,
        "offline",
        "Entering overtime by hand needs the API, so there is nothing here for " +
          "the demo to clear.",
      );
    },
    [isConnected],
  );

  /** A one-off payment. Refuses offline for the same reason as the rest. */
  const setBonus = useCallback(
    async (
      runId: string,
      input: { employeeId: string; amountKobo: number; reason: string },
    ): Promise<BonusChange> => {
      if (isConnected) return payrollApi.setBonus(runId, input);
      throw new ApiError(
        0,
        "offline",
        "Adding a bonus needs the API. It moves gross and the tax on it, and " +
          "the demo has no engine to recompute either.",
      );
    },
    [isConnected],
  );

  const clearBonus = useCallback(
    async (runId: string, employeeId: string): Promise<PreparedRun> => {
      if (isConnected) return payrollApi.clearBonus(runId, employeeId);
      throw new ApiError(0, "offline", "Adding a bonus needs the API.");
    },
    [isConnected],
  );

  /**
   * Somebody's contractual monthly pay, from the payroll table.
   *
   * Refused offline, and for a stronger reason than the two overrides: this
   * writes the **employment record**. A salary changed in browser storage would
   * never reach a payroll run, and unlike a demo leave request it would look
   * exactly like a real pay rise on the screen that shows it.
   */
  const setMonthlyPay = useCallback(
    async (
      runId: string,
      input: { employeeId: string; grossMonthlyKobo: number; reason: string },
    ): Promise<MonthlyPayChange> => {
      if (isConnected) return payrollApi.setMonthlyPay(runId, input);
      throw new ApiError(
        0,
        "offline",
        "Changing somebody's pay needs the API. This writes their employment " +
          "record, and a salary kept in this browser would never reach a real " +
          "payroll.",
      );
    },
    [isConnected],
  );

  const setTaxOverride = useCallback(
    async (
      runId: string,
      input: {
        employeeId: string;
        payeKobo: number;
        reason: string;
        alsoStanding?: boolean;
      },
    ): Promise<TaxOverrideChange> => {
      if (isConnected) return payrollApi.setTaxOverride(runId, input);
      throw new ApiError(
        0,
        "offline",
        "Entering tax by hand needs the API. A figure typed here would recompute " +
          "net pay with no engine to check it against, so the demo will not " +
          "pretend it has.",
      );
    },
    [isConnected],
  );

  /** Clears this period's hand-entered PAYE. Same reasoning as
   *  `setTaxOverride` for why demo mode refuses. */
  const clearTaxOverride = useCallback(
    async (runId: string, employeeId: string): Promise<TaxOverrideChange> => {
      if (isConnected) return payrollApi.clearTaxOverride(runId, employeeId);
      throw new ApiError(
        0,
        "offline",
        "Entering tax by hand needs the API, so there is nothing here for the " +
          "demo to clear.",
      );
    },
    [isConnected],
  );

  return {
    prepare,
    approve,
    cancel,
    exclude,
    putBack,
    setTaxOverride,
    clearTaxOverride,
    setOvertimeOverride,
    clearOvertimeOverride,
    setBonus,
    clearBonus,
    setMonthlyPay,
    connected: isConnected,
  };
}

/* --------------------------------------------------------------- payslips */

export type PayslipRecord = {
  payslip: Payslip | null;
  /**
   * Just enough of the run to place the payslip in time. `PayrollRun` in demo
   * mode (which already has the full run in hand) and `PayslipRunSummary`
   * connected (which now asks for one payslip, not a run) both satisfy this —
   * nothing here reads more than `id`/`period`/`payDate`/`status`.
   */
  run: PayslipRunSummary | null;
  loading: boolean;
  connected: boolean;
  notFound: boolean;
  /**
   * Year-to-date is not available for a single payslip.
   *
   * There is no endpoint for it and summing it would mean fetching every
   * approved run for the year. The demo projects from this month, which it says
   * on screen; connected mode shows nothing rather than a figure somebody might
   * file.
   */
  projectYearToDate: boolean;
};

/**
 * One payslip. `id` is its own id in every real link this app writes; `runId`
 * is now unused for a connected fetch and kept only because demo mode's
 * lookup still benefits from it and `view.tsx` already threads it through.
 *
 * ## Why this used to fetch up to seven runs, and no longer does
 *
 * There was no `GET /payslips/:id` to ask directly, so a connected read
 * fetched the run (with the hint) or searched the newest six runs in turn (a
 * bookmarked link, a payslip mailed out) matching each payslip's own id or its
 * employee id — the latter because the demo's URLs, and every prerendered
 * page, are keyed by employee id. That endpoint exists now, and it settles
 * something the search never could: read as the payslip's own employee, no
 * `VIEW_SALARIES` is required, because it is that employee's own pay. The
 * old path always asked for the whole run and so always needed the
 * permission, which meant an employee could not open their own payslip.
 *
 * Demo mode is unaffected below and keeps matching by either id, since its
 * fixtures and prerendering still use the employee id.
 */
export function usePayslipRecord(
  id: string,
  runId: string | null,
): PayslipRecord {
  const { isConnected } = useSession();
  const demo = useDemoContext();
  const [found, setFound] = useState<{
    id: string;
    payslip: Payslip | null;
    run: PayslipRunSummary | null;
  } | null>(null);

  /* Re-ask when somebody comes back to the window. Not in the key below,
     so the answer is replaced without the screen flashing a skeleton. */
  const revalidation = useRevalidation();
  useEffect(() => {
    if (!isConnected) return;
    let cancelled = false;
    const controller = new AbortController();

    void (async () => {
      try {
        const { payslip, run } = await payrollApi.payslip(
          id,
          controller.signal,
        );
        if (!cancelled) setFound({ id, payslip, run });
      } catch (error) {
        if (error instanceof DOMException && error.name === "AbortError")
          return;
        if (!cancelled) setFound({ id, payslip: null, run: null });
      }
    })();

    return () => {
      cancelled = true;
      controller.abort();
    };
  }, [isConnected, id, revalidation]);

  if (!isConnected) {
    const detail =
      demo.details.find((d) => d.id === runId) ??
      demo.details.find((d) =>
        d.payslips.some((s) => s.id === id || s.employeeId === id),
      ) ??
      null;
    const payslip =
      detail?.payslips.find((s) => s.id === id || s.employeeId === id) ?? null;
    return {
      payslip,
      run: detail ? summarise(detail) : null,
      loading: false,
      connected: false,
      notFound: payslip === null,
      projectYearToDate: true,
    };
  }

  const matched = found !== null && found.id === id;
  return {
    payslip: matched ? found.payslip : null,
    run: matched ? found.run : null,
    loading: !matched,
    connected: true,
    notFound: matched && found.payslip === null,
    projectYearToDate: false,
  };
}

/* --------------------------------------------------------------- utilities */

/** Blockers first, then warnings, then by employee — the order to work through. */
export function orderExceptions(exceptions: RunException[]): RunException[] {
  return [...exceptions].sort((a, b) => {
    if (a.severity !== b.severity) return a.severity === "BLOCKER" ? -1 : 1;
    return a.code.localeCompare(b.code);
  });
}

export const countBySeverity = (exceptions: RunException[]) => ({
  blockers: exceptions.filter((e) => e.severity === "BLOCKER").length,
  warnings: exceptions.filter((e) => e.severity === "WARNING").length,
});
