"use client";

import { useEffect, useState } from "react";
import { ApiError } from "@/lib/api/client";
import {
  payrollApi,
  type PayslipQuote,
  type QuoteBody,
  type QuoteSettings,
} from "@/lib/api/payroll";
import type { PayrollSettings } from "@/lib/payroll/settings";
import { useDebounced } from "@/lib/use-debounced";
import { useSession } from "./session";

/**
 * A payslip for a salary figure, from the one engine that computes payslips.
 *
 * ## What this replaced
 *
 * `web/src/lib/payroll/engine.ts` — a second implementation of Nigerian PAYE,
 * pension and NHF, in floating-point naira, in the browser. It served four
 * screens, and when the Nigeria Tax Act 2025 bands went into the API it was left
 * on the 2011 schedule: all four quoted **₦63,266.67** on ₦500,000 a month where
 * the answer was **₦63,950**. Two implementations of statutory tax is one too
 * many, and the copy that is wrong is always the one on the screen somebody is
 * looking at. It is deleted; this hook is what those screens call instead.
 *
 * ## Demo mode returns nothing, on purpose
 *
 * `available` is false with no API, and every caller renders a sentence rather
 * than a number. There is no honest alternative: a figure computed in the
 * browser would be the deleted engine coming back, and a plausible-looking
 * placeholder next to a salary somebody typed would be read as an answer.
 *
 * The demo payroll run is a different case and takes a different route — it
 * shows **fixed figures generated by the API's engine** (`lib/mock/demo-payslips`)
 * because a payroll demo with no payroll in it demonstrates nothing. Those are
 * labelled illustrative wherever they appear, and they only exist for the demo
 * directory's own salaries. A salary being typed is not one of those.
 *
 * ## Staleness, which is the bug worth spending two lines on
 *
 * Requests are debounced, because a salary field produces six of them on the way
 * to "500000". Debouncing the request is not enough: between a keystroke and the
 * timer firing, the debounced key is unchanged, so a naive `loading` flag stays
 * false and **the previous figure sits on screen beside an input that has already
 * moved**. A wrong salary preview is worse than a spinner.
 *
 * So the request is sent for the *debounced* key and the answer is matched
 * against the *live* one. Anything else in hand is not this question's answer,
 * and `loading` is exactly "the question in hand has no answer yet".
 */

export type QuoteState = {
  quote: PayslipQuote | null;
  loading: boolean;
  error: ApiError | null;
  /** False with no API. The caller must then show no figures at all. */
  available: boolean;
};

const OFFLINE: QuoteState = {
  quote: null,
  loading: false,
  error: null,
  available: false,
};

/**
 * Company settings in the engine's shape.
 *
 * Only for the settings screen, which is previewing a change it has **not
 * saved** — every other caller omits settings so the quote comes back on the
 * company's stored ones, which are what a real run will use. The exception rules
 * are not sent because they decide what stops a run, not what anybody is paid.
 */
export function quoteSettingsFrom(settings: PayrollSettings): QuoteSettings {
  return {
    workingDaysPerMonth: settings.workingDaysPerMonth,
    basicPercent: settings.salarySplit.basic,
    housingPercent: settings.salarySplit.housing,
    transportPercent: settings.salarySplit.transport,
    payeEnabled: settings.paye.enabled,
    pensionEnabled: settings.pension.enabled,
    pensionEmployeeRate: settings.pension.employeeRate,
    pensionEmployerRate: settings.pension.employerRate,
    pensionOnBasic: settings.pension.basis.includes("basic"),
    pensionOnHousing: settings.pension.basis.includes("housing"),
    pensionOnTransport: settings.pension.basis.includes("transport"),
    nhfEnabled: settings.nhf.enabled,
    nhfRate: settings.nhf.rate,
    nhfOnGross: settings.nhf.basis === "gross",
  };
}

/**
 * @param body What to quote, or null when there is nothing to ask yet — a blank
 *   salary field, or a form that has not been touched. Null is not an error and
 *   is not a loading state.
 * @param delay Debounce, in milliseconds. The default suits a figure being
 *   typed; pass 0 where the input is a switch or a dropdown and should answer at
 *   once.
 */
export function usePayslipQuote(body: QuoteBody | null, delay = 350): QuoteState {
  const { isConnected, isLoading } = useSession();
  const [result, setResult] = useState<{
    key: string;
    data: PayslipQuote | null;
    error: ApiError | null;
  } | null>(null);

  /* Serialised so the effect depends on a string rather than on an object the
     caller rebuilds every render — the same reason `usePayComponents` keys on
     JSON. Property order is whatever the caller's literal declares, and a
     literal's order does not change between renders. */
  const key = body === null ? null : JSON.stringify(body);
  const settled = useDebounced(key, delay);
  const wanted = isConnected && !isLoading ? settled : null;

  useEffect(() => {
    if (wanted === null) return;
    const controller = new AbortController();
    let cancelled = false;

    void (async () => {
      try {
        const data = await payrollApi.quote(
          JSON.parse(wanted) as QuoteBody,
          controller.signal,
        );
        if (!cancelled) setResult({ key: wanted, data, error: null });
      } catch (error) {
        if (error instanceof DOMException && error.name === "AbortError") return;
        if (!cancelled) {
          setResult({
            key: wanted,
            data: null,
            error: error instanceof ApiError ? error : null,
          });
        }
      }
    })();

    return () => {
      cancelled = true;
      /* A figure nobody is looking at any more is bandwidth spent on a wrong
         answer. Aborted rather than merely ignored. */
      controller.abort();
    };
  }, [wanted]);

  if (!isConnected) return OFFLINE;

  /* Matched against the LIVE key, never the debounced one. See the note above:
     this is what turns "typing" into a spinner instead of into last keystroke's
     answer wearing this keystroke's label. */
  const matched = result !== null && result.key === key;
  return {
    quote: matched ? result.data : null,
    error: matched ? result.error : null,
    loading: key !== null && !matched,
    available: true,
  };
}
