/**
 * Regenerates `src/lib/reference/banks.ts` from Paystack's public bank list.
 *
 * Run deliberately, review the diff, commit it. Never wired into a build: a bank
 * code that changed silently under a running app is precisely the failure
 * `payments/file.ts` warns about — "a wrong bank code routes money to the wrong
 * institution". A refresh that nobody looked at is the same risk with extra
 * steps.
 *
 *     npm run refresh:banks
 *
 * Prints added, removed and — the one that matters — **changed codes**, because
 * a bank whose code moved is a bank whose existing employee records now carry
 * the old one.
 */

import { readFile, writeFile } from "node:fs/promises";

const SOURCE = "https://api.paystack.co/bank?country=nigeria&perPage=200";
const OUT = new URL("../src/lib/reference/banks.ts", import.meta.url);

type PaystackBank = {
  name: string;
  code: string;
  active: boolean;
  currency: string;
  type: string;
  supports_transfer: boolean;
};

/** Only what a salary can actually be paid into. See the note in banks.ts. */
const payable = (b: PaystackBank) =>
  b.active && b.currency === "NGN" && b.type === "nuban" && b.supports_transfer;

const existing = async (): Promise<Map<string, string>> => {
  try {
    const text = await readFile(OUT, "utf8");
    const found = new Map<string, string>();
    for (const m of text.matchAll(/\{ label: "((?:[^"\\]|\\.)*)", code: "([^"]+)" \}/g)) {
      found.set(m[1]!.replace(/\\"/g, '"'), m[2]!);
    }
    return found;
  } catch {
    return new Map();
  }
};

const response = await fetch(SOURCE);
if (!response.ok) {
  console.error(`Paystack answered ${response.status}. Nothing written.`);
  process.exit(1);
}

const body = (await response.json()) as { data?: PaystackBank[] };
const all = body.data ?? [];
if (all.length === 0) {
  /* An empty list would silently blank the file and leave every bank dropdown
     empty. Refuse rather than write it. */
  console.error("Paystack returned no banks. Nothing written.");
  process.exit(1);
}

const kept = all
  .filter(payable)
  .sort((a, b) => a.name.toLowerCase().localeCompare(b.name.toLowerCase()));

const before = await existing();
const added: string[] = [];
const changed: string[] = [];
for (const bank of kept) {
  const had = before.get(bank.name);
  if (had === undefined) added.push(`${bank.name} (${bank.code})`);
  else if (had !== bank.code) changed.push(`${bank.name}: ${had} -> ${bank.code}`);
}
const names = new Set(kept.map((b) => b.name));
const removed = [...before.keys()].filter((n) => !names.has(n));

const today = new Date().toISOString().slice(0, 10);
const rows = kept
  .map((b) => `  { label: ${JSON.stringify(b.name)}, code: ${JSON.stringify(b.code)} },`)
  .join("\n");

const previous = await readFile(OUT, "utf8").catch(() => "");
/* The header is kept verbatim from the file being replaced, minus the date line,
   so the reasoning written by hand is never lost to a regeneration. */
const header = previous.includes("export type Bank")
  ? previous
      .slice(0, previous.indexOf("export type Bank"))
      .replace(/ \* Fetched \d{4}-\d{2}-\d{2}\.\n/, ` * Fetched ${today}.\n`)
      .replace(/Paystack returns \d+ entries/, `Paystack returns ${all.length} entries`)
      .replace(/keeps the \d+ that are/, `keeps the ${kept.length} that are`)
  : `/** GENERATED by scripts/refresh-banks.mts. Fetched ${today}. */\n\n`;

/**
 * The two exported types.
 *
 * Regenerated with the data, so they cannot drift from it — the preserved header
 * above stops at `export type Bank`, and everything from there down is written
 * by this script. Anything hand-written that belongs in that file belongs here
 * instead.
 */
const types = `export type Bank = { label: string; code: string };

/**
 * A bank a picker may offer: one from the register, or one only a record holds.
 *
 * \`code: null\` is the second case and the whole reason this type is separate
 * from \`Bank\`. See \`banksIncluding\`.
 */
export type BankChoice = { label: string; code: string | null };`;

const footer = `];

/** Code for a bank name, or null when the name is not one we carry. */
export function bankCodeFor(name: string): string | null {
  const needle = name.trim().toLowerCase();
  return (
    NIGERIAN_BANKS.find((b) => b.label.toLowerCase() === needle)?.code ?? null
  );
}

/**
 * The register, plus whatever a record already holds.
 *
 * A stored bank name that is not in this list is the case that matters: an
 * imported record, a name typed before the register was checked in, or an
 * institution that has since been renamed. A picker that simply omits it shows
 * "not known yet" over an account that is being paid every month, and the next
 * person to open that record has been told something false.
 *
 * The appended entry carries **\`code: null\`, never a guess.** \`payments/file.ts\`
 * in the API is blunt about why: a wrong bank code routes money to the wrong
 * institution. A missing code is a gap somebody can close; an invented one is a
 * payment nobody can recall.
 */
export function banksIncluding(current?: string | null): readonly BankChoice[] {
  const trimmed = current?.trim();
  if (!trimmed || bankCodeFor(trimmed) !== null) return NIGERIAN_BANKS;
  return [...NIGERIAN_BANKS, { label: trimmed, code: null }];
}
`;

await writeFile(
  OUT,
  `${header}${types}\n\nexport const NIGERIAN_BANKS: readonly Bank[] = [\n${rows}\n${footer}`,
  "utf8",
);

console.log(`${kept.length} banks written of ${all.length} returned.`);
if (added.length) console.log(`\nAdded (${added.length}):\n  ${added.join("\n  ")}`);
if (removed.length) console.log(`\nRemoved (${removed.length}):\n  ${removed.join("\n  ")}`);
if (changed.length) {
  console.log(`\n!! CODE CHANGED (${changed.length}):\n  ${changed.join("\n  ")}`);
  console.log(
    "\nAn employee record holding the old code will keep holding it. Check\n" +
      "`employees` and `bank_accounts` for the affected bank before the next\n" +
      "payment file goes out.",
  );
}
if (!added.length && !removed.length && !changed.length) console.log("No change.");
